---
output: 
  html_document: 
    keep_md: yes
    self_contained: no
    smart: no
---

```{r setup,include=FALSE}
```

```{r code block 1, echo=FALSE,message = FALSE, warning=FALSE}
library(RMySQL)
library(DBI)
library(ggplot2)
library(plotly)
library(rmarkdown)
names(vignetteEngine(package = 'knitr'))

#Set up database connection
mydb = dbConnect(MySQL(),)

#Query and make tables
a_rs = dbSendQuery(mydb, "SELECT eRAP_ID, admission_datetime, room, report_date FROM tIcuAdmissions;")
admissions_table = fetch(a_rs, n=-1)
admissions_table[,2] <- as.POSIXct(strptime(admissions_table[,2] ,"%Y-%m-%d"))
admissions_table[,4] <- as.POSIXct(strptime(admissions_table[,4] ,"%Y-%m-%d"))

c_rs = dbSendQuery(mydb, "SELECT specimen_ID,eRAP_ID, collection_location, collection_date, sampling_date FROM tStoolCollection;")
collections_table = fetch(c_rs, n=-1)
collections_table[,4] <- as.POSIXct(strptime(collections_table[,4] ,"%Y-%m-%d"))
collections_table[,5] <- as.POSIXct(strptime(collections_table[,5] ,"%Y-%m-%d"))
collections_table[grep("RC", collections_table$specimen_ID),"type"] <- "stool"
collections_table[grep("SW", collections_table$specimen_ID),"type"] <- "swab"

i_rs = dbSendQuery(mydb, "SELECT isolate_ID,eRAP_ID,order_date,collection_date,collection_unit,collection_sourceA,collection_sourceB FROM tIsolates;")
isolates_table = fetch(i_rs,n=-1)
isolates_table[,3] <- as.POSIXct(strptime(isolates_table[,3] ,"%Y-%m-%d"))
isolates_table[,4] <- as.POSIXct(strptime(isolates_table[,4] ,"%Y-%m-%d"))
colnames(isolates_table)[6] <- c("isolate_sourceA")
colnames(isolates_table)[7] <- c("isolate_sourceB")


#Get all CDI isolates by selecting rows with isolate IDs starting with CD
cdi_isolates=isolates_table[grep("CD", isolates_table$isolate_ID),]
cdi_isolates<-cdi_isolates[ cdi_isolates[,4]>as.POSIXct(strptime("2015-09-14","%Y-%m-%d")),]

n_rs = dbSendQuery(mydb, "SELECT eRAP_ID, order_date FROM tCdiNegativeTests;")
negative_table = fetch(n_rs,n=-1)
negative_table[,2] <- as.POSIXct(strptime(negative_table[,2] ,"%Y-%m-%d"))
#Remove everything before september 14th
negative_table<-negative_table[ negative_table[,2]>as.POSIXct(strptime("2015-09-14","%Y-%m-%d")),]

admit_exit_dict = read.csv("/Users/elizabethwebster/Desktop/daily_cdiff_reporting/all_icu_tracking/admit_exit_dict.csv",header=FALSE)
colnames(admit_exit_dict)<-c("Patient.ID","ICU_admit", "ICU", "ICU_exit")
admit_exit_dict[,2]<- as.POSIXct(strptime(admit_exit_dict[,2] ,"%Y-%m-%d"))
admit_exit_dict[,4]<- as.POSIXct(strptime(admit_exit_dict[,4] ,"%Y-%m-%d"))
admit_exit_dict[,1]<- as.factor(admit_exit_dict[,1])

#get exit/entry for everyone with a CDI+ isolate: intersection of admit_exit_dict and cdi_isolates
cdi_peeps <- merge(cdi_isolates,admit_exit_dict,by.x="eRAP_ID",by.y="Patient.ID")

#collections_table
cdi_peeps_coll <- merge(cdi_peeps,collections_table,by.x="eRAP_ID",by.y="eRAP_ID")
colnames(cdi_peeps_coll)[4]<-c("isolate_collection_date")
colnames(cdi_peeps_coll)[13] <- c("sample_collection_date") 

#See if they have any negative tests
cdi_final <- merge(cdi_peeps_coll,negative_table,by.x="eRAP_ID",by.y="eRAP_ID",all.x=TRUE)
colnames(cdi_final)[16] <- c("negative_test_date") 
cdi_final[,1]<-as.factor(cdi_final[,1])

stool_sampling_dates = cdi_final[cdi_final$type == "stool",]
swab_sampling_dates = cdi_final[cdi_final$type == "swab",]
```

```{r code block 2, fig.width=15, fig.height=6,echo=FALSE,message = FALSE, warning=FALSE}

  myplot = 
  ggplot(cdi_final,aes(colour = ICU)) +   
  geom_segment(data = cdi_final,aes(x=ICU_admit, xend=ICU_exit, y=eRAP_ID,yend=eRAP_ID),size=1) +
  geom_point(aes(x=negative_test_date,y=eRAP_ID,colour="Negative CDI Test Date"),color="black",size=1.5,shape=4,na.rm=TRUE) + 
  geom_point(aes(x=isolate_collection_date,y=eRAP_ID,colour="CDI + Isolate Collection Date (all stool)"),color="red",size=1.3,na.rm=TRUE) +
  geom_point(data = stool_sampling_dates,aes(x=sampling_date,y=eRAP_ID,colour ="Stool Sample Taken"),color="blue",shape=17,size=2,na.rm=TRUE) +
  geom_point(data = swab_sampling_dates,aes(x=sampling_date,y=eRAP_ID,colour ="Swab Sample Taken"),color="blue",shape=2,size=2,na.rm=TRUE) +  
  xlab("Period of Stay in ICU for patients with CDI + Isolates") + ylab("Patient ID") +
  ggtitle("Sample and Isolate Tracking for CDI + Patients") +
  guides(fill=guide_legend(title=NULL)) +
  theme_bw() 
  ggplotly(myplot) 
 
```
